import java.applet.Applet;
import java.awt.*;

public class breaking_binary extends Applet
{
	byte age;
	int yCord;
	int ySpace;
	public void paint(Graphics g)
	{
		ySpace = 25;
		age = 120;
		yCord = 50;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		g.drawString("Age is " + age ,50,yCord);
		age = (byte) (age + 1);
		yCord = yCord + ySpace;
		
	}
}
